import { notFound } from 'next/navigation'
import {
  isShareLinkActive,
  loadShareLinkByToken,
} from '@/lib/server/sharing/share-link-repository'
import { resolveSharedEntity, type SharedPayload } from '@/lib/server/sharing/share-resolver'

export const dynamic = 'force-dynamic'

export default async function SharedEntityPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const link = loadShareLinkByToken(token)
  if (!link || !isShareLinkActive(link)) notFound()
  const payload = resolveSharedEntity(link)
  if (!payload) notFound()

  return (
    <main className="min-h-screen bg-[#080a0f] text-white">
      <div className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-5 py-8 sm:px-8 lg:px-10">
        <header className="border-b border-white/10 pb-6">
          <div className="text-[11px] font-700 uppercase tracking-[0.16em] text-emerald-300/80">
            SwarmClaw shared {payload.kind}
          </div>
          <h1 className="mt-3 max-w-3xl font-display text-[28px] font-700 tracking-normal text-white">
            {link.label || payloadTitle(payload)}
          </h1>
          <p className="mt-3 max-w-2xl text-[13px] leading-relaxed text-white/60">
            Public, revocable share link. Runtime secrets, credentials, private files, and hidden control metadata are omitted.
          </p>
        </header>
        {renderBody(payload)}
        <footer className="border-t border-white/10 pt-4 text-[11px] text-white/45">
          Generated by SwarmClaw. This page only contains the entity fields explicitly allowed by the share resolver.
        </footer>
      </div>
    </main>
  )
}

function payloadTitle(payload: SharedPayload): string {
  if (payload.kind === 'mission') return payload.title
  if (payload.kind === 'skill') return payload.name
  return payload.name
}

function formatUsd(n: number): string {
  return `$${n.toFixed(n < 0.01 ? 4 : 2)}`
}

function formatNumber(n: number): string {
  return Math.round(n).toLocaleString()
}

function formatDuration(ms: number): string {
  if (!ms) return '0s'
  if (ms < 1000) return `${ms}ms`
  const sec = Math.round(ms / 1000)
  if (sec < 60) return `${sec}s`
  const min = Math.round(sec / 60)
  if (min < 60) return `${min}m`
  if (min < 60 * 24) return `${Math.round((min / 60) * 10) / 10}h`
  return `${Math.round((min / 1440) * 10) / 10}d`
}

function Stat({ label, value, hint }: { label: string; value: string; hint?: string }) {
  return (
    <div className="rounded-[12px] border border-white/10 bg-white/[0.035] px-4 py-3">
      <div className="text-[10px] font-700 uppercase tracking-[0.12em] text-white/45">{label}</div>
      <div className="mt-2 font-display text-[22px] font-700 tracking-normal text-white">{value}</div>
      {hint ? <div className="mt-1 text-[11px] leading-relaxed text-white/45">{hint}</div> : null}
    </div>
  )
}

function ReportMarkdown({ content }: { content: string }) {
  const lines = content.split('\n')

  return (
    <div className="text-[13px] leading-relaxed text-white/72">
      {lines.map((line, index) => renderReportLine(line, index))}
    </div>
  )
}

function parseNumberedListItem(line: string): { marker: string; text: string } | null {
  const dotIndex = line.indexOf('. ')
  if (dotIndex <= 0 || dotIndex > 3) return null
  for (let i = 0; i < dotIndex; i += 1) {
    const code = line.charCodeAt(i)
    if (code < 48 || code > 57) return null
  }
  return { marker: line.slice(0, dotIndex + 1), text: line.slice(dotIndex + 2) }
}

function renderReportLine(line: string, index: number) {
  const trimmed = line.trim()
  if (!trimmed) return <div key={index} className="h-2" />
  if (trimmed === '---') return <hr key={index} className="my-4 border-white/10" />
  if (trimmed.startsWith('### ')) {
    return <h5 key={index} className="mb-2 mt-4 text-[13px] font-800 text-white">{trimmed.slice(4)}</h5>
  }
  if (trimmed.startsWith('## ')) {
    return <h4 key={index} className="mb-2 mt-5 text-[13px] font-800 uppercase tracking-[0.1em] text-white/70">{trimmed.slice(3)}</h4>
  }
  if (trimmed.startsWith('# ')) {
    return <h3 key={index} className="mb-3 mt-1 font-display text-[18px] font-700 text-white">{trimmed.slice(2)}</h3>
  }
  if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
    return (
      <div key={index} className="my-1 flex gap-2">
        <span className="text-white/40">•</span>
        <span>{trimmed.slice(2)}</span>
      </div>
    )
  }
  const numbered = parseNumberedListItem(trimmed)
  if (numbered) {
    return (
      <div key={index} className="my-1 flex gap-2">
        <span className="min-w-5 text-white/40">{numbered.marker}</span>
        <span>{numbered.text}</span>
      </div>
    )
  }
  return <p key={index} className="my-2">{trimmed}</p>
}

function renderBody(payload: SharedPayload) {
  if (payload.kind === 'mission') {
    const statusTone =
      payload.status === 'running'
        ? 'border-emerald-400/25 bg-emerald-400/10 text-emerald-200'
        : payload.status === 'failed' || payload.status === 'budget_exhausted'
          ? 'border-rose-400/25 bg-rose-400/10 text-rose-200'
          : 'border-white/10 bg-white/[0.04] text-white/70'
    return (
      <section className="flex flex-col gap-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
          <div className="max-w-3xl">
            <div className={`inline-flex rounded-full border px-2.5 py-1 text-[11px] font-800 uppercase tracking-[0.1em] ${statusTone}`}>
              {payload.status.replaceAll('_', ' ')}
            </div>
            <h2 className="mt-4 font-display text-[24px] font-700 tracking-normal text-white">{payload.title}</h2>
            <p className="mt-3 whitespace-pre-wrap text-[14px] leading-relaxed text-white/68">{payload.goal}</p>
          </div>
          <div className="grid min-w-[280px] grid-cols-2 gap-2">
            <Stat label="Turns" value={formatNumber(payload.usage.turnsRun)} hint={payload.budget.maxTurns != null ? `cap ${formatNumber(payload.budget.maxTurns)}` : 'no cap'} />
            <Stat label="Spend" value={formatUsd(payload.usage.usdSpent)} hint={payload.budget.maxUsd != null ? `cap ${formatUsd(payload.budget.maxUsd)}` : 'no cap'} />
            <Stat label="Tokens" value={formatNumber(payload.usage.tokensUsed)} hint={payload.budget.maxTokens != null ? `cap ${formatNumber(payload.budget.maxTokens)}` : 'no cap'} />
            <Stat label="Wallclock" value={formatDuration(payload.usage.wallclockMsElapsed)} hint={payload.budget.maxWallclockSec != null ? `cap ${formatDuration(payload.budget.maxWallclockSec * 1000)}` : 'no cap'} />
          </div>
        </div>
        {payload.successCriteria.length > 0 ? (
          <div className="rounded-[14px] border border-white/10 bg-white/[0.025] p-4">
            <h3 className="text-[12px] font-800 uppercase tracking-[0.12em] text-white/55">Success criteria</h3>
            <ul className="mt-3 grid gap-2 text-[13px] text-white/70 md:grid-cols-2">
              {payload.successCriteria.map((c, i) => (
                <li key={i} className="rounded-[10px] border border-white/10 bg-white/[0.025] px-3 py-2">{c}</li>
              ))}
            </ul>
          </div>
        ) : null}
        {payload.latestReport ? (
          <article className="rounded-[14px] border border-emerald-400/20 bg-emerald-400/[0.04] p-4">
            <div className="text-[11px] font-800 uppercase tracking-[0.12em] text-emerald-200/80">Latest report</div>
            <div className="mt-1 text-[15px] font-800 text-white">{payload.latestReport.title}</div>
            <div className="mt-1 text-[11px] text-white/45">{formatTime(payload.latestReport.at)} - {payload.latestReport.format}</div>
            <div className="mt-4 rounded-[12px] border border-white/10 bg-black/20 px-4 py-3">
              <ReportMarkdown content={payload.latestReport.content} />
            </div>
          </article>
        ) : null}
        {payload.milestones.length > 0 ? (
          <div className="rounded-[14px] border border-white/10 bg-white/[0.025] p-4">
            <h3 className="text-[12px] font-800 uppercase tracking-[0.12em] text-white/55">Milestones</h3>
            <ol className="mt-3 space-y-2">
              {payload.milestones.map((m, i) => (
                <li key={i} className="flex gap-3 rounded-[10px] border border-white/10 bg-white/[0.02] px-3 py-2 text-[12px]">
                  <span className="shrink-0 text-white/40">{formatTime(m.at)}</span>
                  <span className="shrink-0 font-800 text-white/55">{m.kind}</span>
                  <span className="text-white/75">{m.summary}</span>
                </li>
              ))}
            </ol>
          </div>
        ) : null}
        {payload.reports.length > 1 ? (
          <div className="rounded-[14px] border border-white/10 bg-white/[0.025] p-4">
            <h3 className="text-[12px] font-800 uppercase tracking-[0.12em] text-white/55">Earlier reports</h3>
            <div className="mt-3 grid gap-3">
              {payload.reports.slice(1).map((r) => (
                <article key={r.id} className="rounded-[12px] border border-white/10 bg-white/[0.02] p-4">
                  <div className="text-[13px] font-800 text-white">{r.title}</div>
                  <div className="mt-1 text-[11px] text-white/45">{formatTime(r.at)} - {r.format}</div>
                  <div className="mt-3">
                    <ReportMarkdown content={r.content} />
                  </div>
                </article>
              ))}
            </div>
          </div>
        ) : null}
      </section>
    )
  }

  if (payload.kind === 'skill') {
    return (
      <section className="rounded-[14px] border border-white/10 bg-white/[0.025] p-5">
        <h2 className="font-display text-[22px] font-700 text-white">{payload.name}</h2>
        {payload.tags.length > 0 ? (
          <div className="mt-2 flex flex-wrap gap-2">
            {payload.tags.map((t) => (
              <span key={t} className="rounded bg-white/10 px-2 py-0.5 text-xs text-white/70">
                {t}
              </span>
            ))}
          </div>
        ) : null}
        <p className="mt-4 text-[13px] leading-relaxed text-white/65">{payload.description}</p>
        <pre className="mt-6 whitespace-pre-wrap rounded-[12px] border border-white/10 bg-black/20 p-4 text-sm text-white/70">
          {payload.content}
        </pre>
      </section>
    )
  }

  return (
    <section className="rounded-[14px] border border-white/10 bg-white/[0.025] p-5">
      <h2 className="font-display text-[22px] font-700 text-white">{payload.name}</h2>
      {payload.agentName ? (
        <div className="mt-1 text-sm text-white/50">Agent: {payload.agentName}</div>
      ) : null}
      <div className="mt-6 space-y-4">
        {payload.messages.map((m, i) => (
          <article
            key={i}
            className="rounded-[12px] border border-white/10 bg-white/[0.02] p-4"
          >
            <div className="mb-1 flex items-center justify-between text-xs text-white/45">
              <span className="uppercase">{m.role}</span>
              {m.at ? <span>{formatTime(m.at)}</span> : null}
            </div>
            <pre className="whitespace-pre-wrap text-sm text-white/70">{m.text}</pre>
          </article>
        ))}
      </div>
    </section>
  )
}

function formatTime(ts: number): string {
  if (!ts) return ''
  try {
    return new Date(ts).toISOString().replace('T', ' ').slice(0, 19)
  } catch {
    return ''
  }
}
